In [1]:
# Import the modules
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.metrics import confusion_matrix, classification_report

---

## Split the Data into Training and Testing Sets

### Step 1: Read the `lending_data.csv` data from the `Resources` folder into a Pandas DataFrame.

In [2]:
# Read the CSV file from the Resources folder into a Pandas DataFrame
# Define the file path
file_path = "Resources/lending_data.csv"
lending_df = pd.read_csv(file_path)
# Review the DataFrame
lending_df.head()

loan_size  interest_rate  borrower_income  debt_to_income  num_of_accounts  \
0    10700.0          7.672            52800        0.431818                5   
1     8400.0          6.692            43600        0.311927                3   
2     9000.0          6.963            46100        0.349241                3   
3    10700.0          7.664            52700        0.430740                5   
4    10800.0          7.698            53000        0.433962                5   

   derogatory_marks  total_debt  loan_status  
0                 1       22800            0  
1                 0       13600            0  
2                 0       16100            0  
3                 1       22700            0  
4                 1       23000            0

### Step 2: Create the labels set (`y`)  from the “loan_status” column, and then create the features (`X`) DataFrame from the remaining columns.

In [3]:
# Separate the data into labels and features

# Separate the y variable, the labels
y = lending_df["loan_status"]

# Separate the X variable, the features
X = lending_df.drop(columns=["loan_status"])
X.head()

loan_size  interest_rate  borrower_income  debt_to_income  num_of_accounts  \
0    10700.0          7.672            52800        0.431818                5   
1     8400.0          6.692            43600        0.311927                3   
2     9000.0          6.963            46100        0.349241                3   
3    10700.0          7.664            52700        0.430740                5   
4    10800.0          7.698            53000        0.433962                5   

   derogatory_marks  total_debt  
0                 1       22800  
1                 0       13600  
2                 0       16100  
3                 1       22700  
4                 1       23000

In [4]:
# Review the y variable Series
y_info = {
    "Data Type": y.dtype,
    "Unique Values": y.unique(),
    "Value Counts": y.value_counts(),
    "First Few Rows": y.head()
}

y_info

{'Data Type': dtype('int64'),
 'Unique Values': array([0, 1]),
 'Value Counts': loan_status
 0    75036
 1     2500
 Name: count, dtype: int64,
 'First Few Rows': 0    0
 1    0
 2    0
 3    0
 4    0
 Name: loan_status, dtype: int64}

In [6]:
# Review the X variable DataFrame
X_info = {
    "Shape": X.shape,
    "Data Types": X.dtypes,
    "Missing Values": X.isnull().sum(),
    "Summary Statistics": X.describe(),
    "First Few Rows": X.head()
}


### Step 3: Split the data into training and testing datasets by using `train_test_split`.

In [8]:
# Import the train_test_learn module
from sklearn.model_selection import train_test_split

# Split the data using train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

# Assign a random_state of 1 to the function
split_info = {
    "X_train Shape": X_train.shape,
    "X_test Shape": X_test.shape,
    "y_train Shape": y_train.shape,
    "y_test Shape": y_test.shape
}

split_info

{'X_train Shape': (62028, 7),
 'X_test Shape': (15508, 7),
 'y_train Shape': (62028,),
 'y_test Shape': (15508,)}

---

## Create a Logistic Regression Model with the Original Data

###  Step 1: Fit a logistic regression model by using the training data (`X_train` and `y_train`).

In [9]:
# Import the LogisticRegression module from SKLearn
from sklearn.linear_model import LogisticRegression

# Instantiate the Logistic Regression model
logistic_model = LogisticRegression(random_state=1)
# Assign a random_state parameter of 1 to the model
logistic_model = LogisticRegression(random_state=1)

# Fit the model using training data
logistic_model.fit(X_train, y_train)

# Display model coefficients
logistic_model.coef_, logistic_model.intercept_

(array([[ 4.65493180e-03, -1.21882487e-03, -1.16564683e-03,
          3.10079035e-01, -1.39173076e-01,  1.34396997e+00,
          2.29851126e-04]]),
 array([-4.90824631e-08]))

### Step 2: Save the predictions on the testing data labels by using the testing feature data (`X_test`) and the fitted model.

In [10]:
# Make a prediction using the testing data
y_pred = logistic_model.predict(X_test)
y_pred[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Step 3: Evaluate the model’s performance by doing the following:

* Generate a confusion matrix.

* Print the classification report.

In [11]:
# Generate a confusion matrix for the model
conf_matrix = confusion_matrix(y_test, y_pred)

# Convert confusion matrix to a DataFrame for better visualization
conf_matrix_df = pd.DataFrame(
    conf_matrix, 
    index=["Actual 0", "Actual 1"], 
    columns=["Predicted 0", "Predicted 1"]
    )


In [12]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))


              precision    recall  f1-score   support

           0       1.00      0.99      1.00     15001
           1       0.86      0.94      0.90       507

    accuracy                           0.99     15508
   macro avg       0.93      0.97      0.95     15508
weighted avg       0.99      0.99      0.99     15508



### Step 4: Answer the following question.

**Question:** How well does the logistic regression model predict both the `0` (healthy loan) and `1` (high-risk loan) labels?

**Answer:** The Model performs well with an overall of 99.2% accuracy Therefore making it strongg in detecting high sink loans 

---